### ISSUE TITLE
Copyright notice and contact info are out of date

### ISSUE THREAD

**Issue by nelstrom** [universal-ctags/homebrew-universal-ctags#3]
I'd like to try out universal-ctags, so I've just issued the following commands:

```
$ brew unlink ctags
$ brew tap universal-ctags/universal-ctags
$ brew install --HEAD universal-ctags
```

This seems to have worked. I get a different message now when I run `ctags --help`:

```
$ ctags --help
Universal Ctags Development, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jul 20 2015, 16:56:17
  Addresses: <dhiebert@users.sourceforge.net>, https://github.com/universal-ctags/ctags
  Optional compiled features: +wildcards, +regex, +debug, +option-directory, +coproc
```

I think that the contact details and copyright notice are wrong.

I'm not sure if this issue belongs on `homebrew-universal-ctags` or one of the other repos managed by this organisation. If I should have raised this issue on another repo, let me know and I'll adjust.

**Comment by ffes** [comment]
Yes, you are right. And as you assumed correctly, that is because the main repo has not released a version yet. I am not a Mac guy, but if I understand correctly this homebrew tap is just an easy way to get the a compiled version of the master (aka development) branch of Universal Ctags repo on your Mac. But @cweagans knows all the details. His is the author of this tap.

**Comment by cweagans** [comment]
This Homebrew Tap just compiles universal ctags on a user's machine. The Ctags copyright information is outside the scope of the tap - it's something that would need to be changed in the ctags repo.

**Comment by nelstrom** [comment]
Ok, thanks for clarifying that. I'll close this issue.
